x = int(input('Enter 1st no.: '))
y = int(input('Enter 2nd no.: '))
print("Arithmetic Operators: ")
print("A+B=",x+y)
print("A-B=",x-y)
print("A*B=",x*y)
print("A/B=",x/y)
print("A%B=",x%y)
print("A//B=",x//y)
print("A**B=",x**y)
print("Assignment operators: ")
x+=y
print("A+=B: ",x)
x-=y
print("A-=B: ",x)
x*=y
print("A*=B: ",x)
x/=y
print("A/=B: ",x)
x%=y
print("A%=B: ",x)
x=y
print("A=B=",x)
print("Comparison operators: ")
print("x==y: ",x==y)
print("x!=y: ",x!=y)
print("x<y: ",x<y)
print("x>y: ",x>y)
print("x<=y: ",x<=y)
print("x>=y: ",x>=y)
print("Logical operators: ")
print(x > 3 and y < 10)
print(x > 3 or x < 10)
print(not(x < 5 and x < 10))
print("Bitwise operators: ")
print("a & b =", x & y)
print("a | b =", x | y)
print("~x =", ~x)
print("a ^ b =", x ^ y)
print("a >> 1 =", x >> 1)
print("a << 1 =", x << 1)
print("Identity operators: ")
print(x is y)
print(x is not y)
print("Membership operators: ")
a=[1,2,3]
print(1 in a)
print(4 not in a)